USE [master]
GO

/****** Object:  Database [EOR]    Script Date: 12/02/2023 11:03:33 ******/
CREATE DATABASE [EOR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EOR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\EOR.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EOR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\EOR_log.ldf' , SIZE = 112384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EOR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EOR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EOR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EOR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EOR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EOR] SET ARITHABORT OFF 
GO

ALTER DATABASE [EOR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EOR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EOR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EOR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EOR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EOR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EOR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EOR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EOR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EOR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EOR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EOR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EOR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EOR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EOR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EOR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EOR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EOR] SET RECOVERY FULL 
GO

ALTER DATABASE [EOR] SET  MULTI_USER 
GO

ALTER DATABASE [EOR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EOR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EOR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EOR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EOR] SET  READ_WRITE 
GO

